[project]
name = "decentralized-subscription-service"
requirements = []
costs_version = 2

[contracts.subscription-service]
path = "contracts/subscription-service.clar"
depends_on = []

[contracts.subscription-treasury]
path = "contracts/subscription-treasury.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
